name: basic
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  intl: ^0.19.0
  collection: ^1.18.0
  csv: ^5.1.1
  http: ^1.1.2
  args: ^2.4.2
  logger: ^2.0.2+1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
